name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set environment variables from secrets
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
        run: echo "Environment variables set for testing"

      # - name: Verify Environment Variables
      #   run: |
      #     echo "DB_USER: $DB_USER"
      #     echo "DB_PASS: $DB_PASS"
      #     echo "DB_HOST: $DB_HOST"
      #     echo "DB_NAME: $DB_NAME"
      #     echo "DB_SSLMODE: $DB_SSLMODE"
